/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package texteditorproject;

/**
 *
 * @author lenovo
 */
public class EditorUI extends javax.swing.JFrame {
    private int currentSearchIndex = 0;
    private final DocumentManager dm;
    private final EditorHistory history = new EditorHistory();
    
    public EditorUI() {
        initComponents();
        
        dm = new DocumentManager(textArea);

        javax.swing.JPanel topPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));
        topPanel.add(chkDarkMode);
        topPanel.add(btnOpen);
        topPanel.add(btnSave);
        topPanel.add(btnSaveAs);
        topPanel.add(btnUndo);
        topPanel.add(btnClose);

        javax.swing.JPanel findPanel = new javax.swing.JPanel(new java.awt.BorderLayout(5, 0));
        javax.swing.JPanel findRight = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 2));
        findRight.add(chkCaseSensitive);
        findRight.add(btnFind);
        findRight.add(btnFindNext);
        findPanel.add(txtSearch, java.awt.BorderLayout.CENTER);
        findPanel.add(findRight, java.awt.BorderLayout.EAST);

        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        getContentPane().add(findPanel, java.awt.BorderLayout.SOUTH);

        setMinimumSize(new java.awt.Dimension(500, 350));
        history.pushMemento(new EditorMemento(""));
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSaveAs = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        chkCaseSensitive = new javax.swing.JCheckBox();
        btnFind = new javax.swing.JButton();
        chkDarkMode = new javax.swing.JCheckBox();
        btnFindNext = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        textArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(textArea);

        btnOpen.setText("Open File");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSaveAs.setText("Save As");
        btnSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAsActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnUndo.setText("Undo");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        chkCaseSensitive.setText("Case-sensitive");

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        chkDarkMode.setText("Dark Mode");
        chkDarkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDarkModeActionPerformed(evt);
            }
        });

        btnFindNext.setText("Find Next");
        btnFindNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chkDarkMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveAs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCaseSensitive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFindNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnUndo)
                    .addComponent(btnSaveAs)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpen)
                    .addComponent(chkDarkMode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkCaseSensitive)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindNext, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        Command openCmd = new OpenCommand(dm);
        openCmd.execute();
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Command saveCmd = new SaveCommand(dm);
        saveCmd.execute();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAsActionPerformed
        Command saveAsCommand = new SaveAsCommand(dm);
        saveAsCommand.execute();
    }//GEN-LAST:event_btnSaveAsActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed
    
    //history den bir önceki durumu alır ve metni o hale geri döndürür
    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        EditorMemento memento = history.undoMemento();
        if (memento != null) {
            textArea.setText(memento.getText());
        }
    }//GEN-LAST:event_btnUndoActionPerformed
    
    //her kelime veya satır sonunda mevcut metin durumunu history ye kaydeder
    private void textAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyReleased
        if (evt.getKeyCode() == 32 || evt.getKeyCode() == 10) {
            history.pushMemento(new EditorMemento(textArea.getText()));
        }
    }//GEN-LAST:event_textAreaKeyReleased

    //seçilen stratejiye göre (case sensitive/insensitive) metinde arama yapar
    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String word = txtSearch.getText(); 
        String text = textArea.getText();  
        boolean isCaseSensitive = chkCaseSensitive.isSelected(); 

        if (word.isEmpty()) {
            return; // Arama kutusu boşsa hiçbir şey yapmadan çık
        }

        // Harf duyarlılığı seçili değilse, sorunsuz bulabilmek için ikisini de küçük harfe çeviriyoruz
        if (!isCaseSensitive) {
            text = text.toLowerCase();
            word = word.toLowerCase();
        }

        // "Find" (İlk Bul) butonuna basıldığı için aramaya her zaman metnin en başından (0. index) başlıyoruz
        currentSearchIndex = text.indexOf(word, 0);

        if (currentSearchIndex != -1) {
            // Kelime metnin içinde bulundu! O kısmı seçip mavi ile vurguluyoruz
            textArea.setCaretPosition(currentSearchIndex + word.length());
            textArea.select(currentSearchIndex, currentSearchIndex + word.length());
            textArea.requestFocus();

            // "Find Next" butonunun kaldığı yeri bilmesi için index'i kelimenin bittiği yere kaydırıyoruz
            currentSearchIndex += word.length(); 
        } else {
            // Kelime metnin hiçbir yerinde yok
            javax.swing.JOptionPane.showMessageDialog(this, "Kelime bulunamadı!");
            currentSearchIndex = 0; // Bulunamadıysa hafızayı sıfırla
        }
    }//GEN-LAST:event_btnFindActionPerformed

    //Singleton SettingsManager üzerinden dark mode durumunu günceller ve temayı uygular
    private void chkDarkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDarkModeActionPerformed
        // 1. Kutucuğun seçili olma durumunu (true/false) Singleton'a gönder
        SettingsManager.getInstance().setDarkMode(chkDarkMode.isSelected());

        // 2. Yeni temayı metin alanımıza (textArea) uygula
        SettingsManager.getInstance().applyTheme(textArea);

        // 3. Java'nın ekranı zorla güncellemesini sağla (Önceki sorunu engelleyecek kısım)
        textArea.setOpaque(true);
        textArea.repaint();
    }//GEN-LAST:event_chkDarkModeActionPerformed

    private void btnFindNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindNextActionPerformed
        String word = txtSearch.getText(); 
        String text = textArea.getText();  
        boolean isCaseSensitive = chkCaseSensitive.isSelected(); 

        if (word.isEmpty()) {
            return; // Kutu boşsa hiçbir şey yapma
        }

        if (!isCaseSensitive) {
            text = text.toLowerCase();
            word = word.toLowerCase();
        }

        // DİKKAT: Burada '0' yerine 'currentSearchIndex' kullanıyoruz. 
        // Yani aramaya en baştan değil, hafızada kaldığımız yerden devam ediyor!
        currentSearchIndex = text.indexOf(word, currentSearchIndex);

        if (currentSearchIndex != -1) {
            // Sonraki kelime bulundu! Vurgula.
            textArea.setCaretPosition(currentSearchIndex + word.length());
            textArea.select(currentSearchIndex, currentSearchIndex + word.length());
            textArea.requestFocus();

            // Bir sonraki arama için index'i yine kelimenin sonuna kaydır
            currentSearchIndex += word.length(); 
        } else {
            // Kelime kalmadıysa uyarı ver ve hafızayı sıfırlayıp başa sar
            javax.swing.JOptionPane.showMessageDialog(this, "Metnin sonuna ulaşıldı. Aramaya baştan başlanacak.");
            currentSearchIndex = 0; 
        }
    }//GEN-LAST:event_btnFindNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFindNext;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAs;
    private javax.swing.JButton btnUndo;
    private javax.swing.JCheckBox chkCaseSensitive;
    private javax.swing.JCheckBox chkDarkMode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
